### PR TITLE
fix(logging): do not log 40x responses as errors

### LINKED ISSUE #180: 404 ref not found errors should not be logged at error level
**Description**
If helix-dispatch is called with an non-existing branch/ref name, it will log an `error` level log message upon getting a 404 from helix-services/resolve-git-ref:

https://github.com/adobe/helix-dispatch/blob/master/src/fetchers.js#L307

**To Reproduce**
1. Go to 'https://unknown--myrepo--myuser.project-helix.page/'
2. Log into Coralogix and observe error:
```json
{
  "level": " error", 
  "message": "Unable to resolve branch name 404 ref not found", 
  "ow": {
    "actionName": " /helix/helix-services-private/dispatch@3.0.8", 
    (...)
  }, 
  "timestamp": " 2020-02-12T00:29:02.168896173Z"
}
```
**Expected behavior**
An `info` level log message would be more appropriate for errors with status codes below 500.

**Additional context**
Other Helix services have been changed to behave this way, see e.g.
https://github.com/adobe/helix-word2md/commit/6a0001ed42c781c0fe305698416662c8b4b9e81e

### PR DESCRIPTION
**Pull request by rofe**
Fix #180

### CODE REVIEW

File: src/fetchers.js [hunk 1]
```diff
@@ -304,9 +304,10 @@ async function resolveRef(opts, log) {
         branch: ref,
       };
     }
-    log.error(`Unable to resolve branch name ${res.statusCode} ${res.body}`);
+    const level = (!res.statusCode || res.statusCode >= 500) ? 'error' : 'info';
```
Comment (trieloff) [inline src/fetchers.js]: This looks like a hack that is a bit too clever – the most likely reason is that you want to keep the line coverage up by avoiding an if statement, so that you don't have to add a new test case.

Comment (rofe) [reply src/fetchers.js]: Actually, that wasn't the reason 😉 I just wanted to keep the footprint as small as possible. And the exact same "hack" already got approved by @tripodsan in https://github.com/adobe-private/helix-googledocs2md/pull/87.

But if you prefer, I can add an `if` and of course a test.

Comment (trieloff) [reply src/fetchers.js]: I would prefer, but don't insist on, that.

Comment (tripodsan) [reply src/fetchers.js]: I'm ok with that....we could also mandate the 100% statement coverage, then the syntax doesn't matter.
